service/docs/getting-started.md, service/grails-app/conf/application.yml
Change foliodev to olfdev according to 'getting-started' and fix some typos
=> Alfons minor doc update

scripts/dev_submit_pkg.sh, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/domain/org/olf/kb/Identifier.groovy, service/grails-app/domain/org/olf/kb/IdentifierNamespace.groovy, service/grails-app/domain/org/olf/kb/TitleInstance.groovy, service/grails-app/domain/org/olf/kb/Work.groovy, service/grails-app/migrations/create-remote-kb.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy
This commit adds fieds to the subscription data - specifically
Date cancellationDeadline
RefdataValue renewalPriority
RefdataValue agreementStatus
RefdataValue isPerpetual
Also fix the URL mapping for creating new refdata values via web service calls - this reinstates the creation of type data on dev_submit_pkg.sh
=> Provide extra fields to subscription UX

service/grails-app/domain/org/olf/erm/SAEventHistory.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/domain/org/olf/folder/Node.groovy, service/grails-app/migrations/create-remote-kb.groovy, service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
=> More fields for ui-erm - expand refdata fields and add contentReviewNeeded

service/docs/getting-started.md
=> Updated the docs to show the various ways to run / build the app.

service/build.gradle, service/grails-app/domain/org/olf/general/RefdataValue.groovy
Fixes issue with nested refdata editing.
=> Add @BindUsingWhenRef from new toolkit release.

service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
Updated the defaults based on the values [requested in UIER-4](https://issues.folio.org/browse/UIER-4).
=> Updated agreement RefdataValue defaults

service/src/main/okapi/ModuleDescriptor-template.json
Quick update to hotfix the resources path for Okapi.
=> Fixed /resource endpoint path

service/grails-app/domain/org/olf/kb/ErmResource.groovy
Just looking to get some values that I can key off of for the E-resource type filtering in [UIER-2](https://issues.folio.org/browse/UIER-2)
=> ErmResource: Added defaults for 'type' RDV

service/grails-app/domain/org/olf/kb/ErmResource.groovy
=> Revert "ErmResource: Added defaults for 'type' RDV"

service/grails-app/services/org/olf/KbHarvestService.groovy
=> Remove alert that KbHarvest service is triggering.

scripts/dev_submit_pkg.sh, service/grails-app/conf/application-vagrant-db.yml, service/grails-app/conf/application.yml, service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/migrations/initial-model.groovy, service/grails-app/views/entitlement/_entitlement.gson
Fixes for UIER-14 - Provide startDate, endDate, contentUpdated and is available flag
=> Extra entitlement fields as per UIER-14

service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/migrations/docs.groovy, service/grails-app/migrations/initial-model.groovy
add column sa_license_note to initial-model.groovy
=> ERM-46: add String licenseNote to SubscriptionAgreement

service/build.gradle, service/gradle.properties, service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy, service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/domain/org/olf/erm/HoldingsCoverage.groovy, service/grails-app/domain/org/olf/kb/CoverageStatement.groovy, service/grails-app/domain/org/olf/kb/ErmResource.groovy, service/grails-app/domain/org/olf/kb/PackageContentItem.groovy, service/grails-app/migrations/coverage-unification.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/KbHarvestService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/views/abstractCoverageStatement/_abstractCoverageStatement.gson, service/grails-app/views/coverageStatement/_coverageStatement.gson, service/grails-app/views/entitlement/_entitlement.gson, service/grails-app/views/ermResource/_ermResource.gson, service/grails-app/views/holdingsCoverage/_holdingsCoverage.gson, service/grails-app/views/packageContentItem/_packageContentItem.gson, service/grails-app/views/platformTitleInstance/_platformTitleInstance.gson, service/grails-app/views/titleInstance/_titleInstance.gson, service/src/main/groovy/org/olf/kb/AbstractCoverageStatement.groovy
Adds custom coverage for Agreement Lines. And also supplies those against the resources in certain contexts.
=> Feature/erm 65/coverage changes

NEWS.md
Release 1.4.0 Including
* ERM-115 Provide correct data for agreement line
* ERM-111 Build Settings Page
* ERM-112 Build Wrapper Component for supression
* ERM-113 Use Wrapper Component in Agreements
* ERM-114 Write tests
* ERM-98 Rendering Controlling Terms License
* ERM-127 Resources with no coverage set should not display
* ERM-110 Agreement Detail record - View attached EBSCO eResource
* ERM-109 Support the ability to create an agreement from eHoldings
* ERM-108 Supress agreements app functions
* ERM-64 Show Controlling License Terms
=> Issue version 1.4.0

Vagrantfile
- Old versions have a broken eholdings setup
=> Update folio testing VM lock

service/build.gradle
=> Honours case entry for RefdataValues.

service/.gitignore, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/domain/org/olf/general/DocumentAttachment.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/suppl-docs.groovy, service/grails-app/views/documentAttachment/_documentAttachment.gson, service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
All work carried out by @CalamityC
* add .DS_Store to .gitignore
* change rendering in views/documentAttachment/_documentAttachment.gson
* add supplementaryDocs to
views/subscriptionAgreement/_subscriptionAgreement.gson
* add supplementaryDocs to SubscriptionAgreement.groovy
* create suppl-docs.groovy and add to module-tenant-changelog.groovy
=> Re-authoring Claudia's PR

Vagrantfile
Bumped the version to incorporate the latest notes related permission that were added to the backend
=> bump vm verision to 2294

scripts/kbart.sh, scripts/titles.sh, service/grails-app/controllers/org/olf/ExportController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/services/org/olf/ExportService.groovy
This is ready for code review ERM-265
=> ERM-265: Add exportcontroller for JSON export

scripts/kbart.sh, scripts/titles.sh, scripts/titles4agreement.sh, service/grails-app/controllers/org/olf/ExportController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/ExportService.groovy, service/grails-app/views/ermResource/_ermResource.gson, service/grails-app/views/export/_exportEntry.gson, service/grails-app/views/export/index.gson, service/grails-app/views/titleInstance/_titleInstance.gson, service/src/main/groovy/org/olf/export/KBart.groovy, service/src/main/groovy/org/olf/export/KBartExport.groovy
This fixes 265 and includes code changes for ERM-215,  327, 328, 329, and 330.  QA only for 265 for now
=> This actually fixes ERM-265

service/grails-app/views/export/_exportEntry.gson
change export view to test for customCoverage
=> add test for customCoverage: fixes ERM-385

service/src/main/groovy/org/olf/export/KBart.groovy
This fixes ERM-387.   Adds test for customCoverage and populates num first/last issue/volume fields
=> add test for customCoverage in transform method

service/.gitignore, service/grails-app/conf/logback.groovy, service/grails-app/domain/org/olf/kb/TitleInstance.groovy, service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/KbHarvestService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy, service/src/main/groovy/org/olf/dataimport/erm/ContentItem.groovy, service/src/main/groovy/org/olf/dataimport/erm/CoverageStatement.groovy, service/src/main/groovy/org/olf/dataimport/erm/Identifier.groovy, service/src/main/groovy/org/olf/dataimport/erm/PackageProvider.groovy, service/src/main/groovy/org/olf/dataimport/erm/PlatformTitileInstance.groovy, service/src/main/groovy/org/olf/dataimport/erm/TitleInstance.groovy, service/src/main/groovy/org/olf/dataimport/internal/InternalPackageImpl.groovy
Provides functionality for [ERM-338] and hopefully fixes [ERM-440]
=> Feature/import validation/erm 338

service/grails-app/conf/logback.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
* Skip deleted TIPPs
* guess missing accessEnd dates and log info
=> ERM 546: Interpret <status> element on GOKb TIPP

service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy
Also move isNull further up to make it quicker to filter ouor list.
=> isNull set on package.

service/grails-app/views/entitlement/_externalEntitlement.gson
[Fixes this bug reported by Khalilah](https://folio-project.slack.com/archives/CH259V2JY/p1575305152000600)
=> Fixed lines/owner external entitlement rendering

service/src/main/groovy/org/olf/export/KBart.groovy
=> PR for ERM-623: Fix for KBART export

service/grails-app/controllers/org/olf/UrlMappings.groovy
add alias for all resources to UrlMappings
=> ERM-680 Backend change

service/grails-app/controllers/org/olf/PackageController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/domain/org/olf/general/jobs/KbartImportJob.groovy, service/grails-app/migrations/update-mod-agreements-2-1.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/grails-app/views/kbartImportJob/_kbartImportJob.gson, service/src/main/groovy/org/olf/dataimport/internal/PackageContentImpl.groovy
Creates a tsv parse endpoint, and a KBART import job class. Changes made to import service and ingest service to allow KBART files to utilise these.
=> PR for backend part of ERM-685

service/grails-app/services/org/olf/TitleInstanceResolverService.groovy
Small change to hopefully fix bug that crops up in LAS:eR integration and KBART import testing
=> changed list instantiation to collection

service/src/main/groovy/org/olf/export/KBart.groovy
* add monograph resource to the kbartList even if no coverage exists
=> ERM-767 Monograph resources are not exported in KBART format

service/src/main/groovy/org/olf/export/KBart.groovy
* add kbart columns to the kbart object
=> ERM-689 Add monograph fields to KBART export

service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-2-3.groovy
- Updated column pd_description to have type `text` instead of of `VARCHAR(255)`
=> ERM-786: Updated column type for agreement custom properties

service/build.gradle, service/grails-app/controllers/org/olf/RefdataController.groovy, service/grails-app/domain/org/olf/erm/AgreementRelationship.groovy, service/grails-app/domain/org/olf/erm/LicenseAmendmentStatus.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreementOrg.groovy, service/grails-app/domain/org/olf/general/jobs/PersistentJob.groovy, service/grails-app/domain/org/olf/kb/IdentifierOccurrence.groovy, service/grails-app/domain/org/olf/kb/TitleInstance.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-2-2.groovy
* add migrations update-mod-agreements-2-2.groovy
* make various refdata categories have a defaultInternal value of true
* include web-toolkit-ce 4.0.2 in build.gradle
* add delete method to refdata controller
=> ERM-735 Separate refdata categories into internal and user lists

Jenkinsfile
Add Jenkins Stage KubeDeploy within pipline.
=> FOLIO-2546: Add Jenkins Stage KubeDeploy within pipline.

Vagrantfile, service/build.gradle, service/grails-app/domain/org/olf/erm/AlternateName.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/migrations/update-mod-agreements-2-3.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/views/alternateNames/_alternateNames.gson, service/grails-app/views/embargoStatement/_embargoStatement.gson, service/grails-app/views/export/_exportEntry.gson, service/grails-app/views/packageContentItem/_packageContentItem.gson, service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson, service/src/main/groovy/org/olf/dataimport/erm/ContentItem.groovy, service/src/main/groovy/org/olf/export/KBart.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
* switch alternateNames from array of strings to array of objects
=> refs ERM-827

service/grails-app/domain/org/olf/erm/RemoteLicenseLink.groovy, service/grails-app/migrations/update-mod-agreements-2-3.groovy
* change RemoteLicenseLink.groovy and migrations file
=> ERM-826 RemoteLicenseLink.Status refdata category should be "internal"

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
=> ERM-547: bugfix

service/grails-app/domain/org/olf/kb/PackageContentItem.groovy, service/grails-app/domain/org/olf/kb/PlatformTitleInstance.groovy, service/grails-app/domain/org/olf/kb/TitleInstance.groovy, service/grails-app/views/entitlement/_externalEntitlement.gson, service/grails-app/views/packageContentItem/_packageContentItem.gson, service/grails-app/views/platformTitleInstance/_platformTitleInstance.gson, service/grails-app/views/titleInstance/_titleInstance.gson, service/src/main/groovy/org/olf/general/StringUtils.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Added code to truncate PTI and PCI names to keep below 255 chars, method to get full names if needed. Added specific code to TI display name.
=> ERM-834, ERM-836

Vagrantfile, service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/domain/org/olf/kb/ErmResource.groovy, service/grails-app/migrations/update-mod-agreements-2-3.groovy, service/grails-app/views/entitlement/_entitlement.gson, service/grails-app/views/entitlement/_externalEntitlement.gson, service/grails-app/views/ermResource/_ermResource.gson
* add suppressFromDiscovery property to entitlement
* add column ent_suppress_discovery to entitlement
* add suppressFromDiscovery property to entitlement templates
* add suppressFromDiscovery property to ErmResource
* add column res_suppress_discovery to erm_resource
* add suppressFromDiscovery property to ermResource template
=> ERM-894 ERM-895 Add "Suppress from discovery" property

service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/domain/org/olf/kb/ErmResource.groovy, service/grails-app/migrations/update-mod-agreements-2-3.groovy, service/grails-app/views/entitlement/_entitlement.gson, service/grails-app/views/entitlement/_externalEntitlement.gson, service/grails-app/views/ermResource/_ermResource.gson
* add tags support for erm resources
* add tags support for agreement lines
=> ERM-896 ERM-897 add support for tags

service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleEnricherService.groovy, service/src/main/groovy/org/olf/dataimport/erm/ContentItem.groovy, service/src/main/groovy/org/olf/dataimport/internal/PackageSchema.groovy
Added sourceIdentifier to the ContentItemSchema
Tweaked enrichment saving to allow logging of those calls which did not update anything
=> ERM-910: fix to import code bug introduced by ERM-681

service/grails-app/services/org/olf/TitleEnricherService.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Now when encountering a journal entry the process does not attempt to save the empty values map.
=> ERM-681: BugFix for attempted saving on journal entries

service/grails-app/domain/org/olf/erm/HoldingsCoverage.groovy, service/grails-app/domain/org/olf/erm/Period.groovy, service/grails-app/domain/org/olf/kb/CoverageStatement.groovy
Noticed with latest eclipse compiler.
=> Ensure class names used in statics

service/src/main/groovy/org/olf/export/KBart.groovy
* add getIdentifierValue method to KBart.groovy and use it for print / online resources and relatedTitles
=> ERM-775 Use information from siblingInstances in KBART export

service/grails-app/views/export/_exportEntry.gson
removed null check as groovy truth meant it didn't display when false
=> ERM-930: SuppressFromDiscovery behaviour tweak

service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/views/entitlement/_externalEntitlement.gson
* add authority and reference property to packageData array in entitlement
* change identifiers schema for external eresources in entitlement
* fix missing owner name in externalEntitlement template
=> ERM-948 Enhance eHoldings display in dedicated Agreement Line view

service/grails-app/views/comparison/compare.gson
Fix: [ERM 977]
Make the embargo field selections null-safe.
=> Null safe.

service/grails-app/views/comparison/compare.gson
- add the titleInstance longName to the output
- add the platformTitleInstance.url to the availability
- correct spelling of occurrences
=> Minor tweaks to comparison output

service/grails-app/views/comparisonPoint/_comparisonPoint.gson
ComparisonJob now renders its comparisonPoints with a slightly expanded titleList, containing id, class and name.
=> Added comparisonPoint view to expand titleList information

service/grails-app/views/comparison/compare.gson
Added:
* Identifiers
* Resource type
* Resource subtype
Also moved where longName is added to keep all additions in one place
=> ERM-992: Extend TI info in comparison

service/grails-app/views/comparison/compare.gson
Tweak to append ti id onto ti name for internal matching purposes.
=> ERM-994: Comparison no longer treats two separate resources with same title as the same

service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
- Added null check to items expansion
=> ERM-1154: Agreement couldn't POST without items array

service/src/main/okapi/ModuleDescriptor-template.json
Quite possible fix for ERM-1079 too
=> ERM-972: Missing permission definition

service/build.gradle, service/grails-app/conf/logback.groovy, service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/controllers/org/olf/EntitlementLogEntryController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/domain/org/olf/erm/EntitlementLogEntry.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/init/org/olf/Application.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-3-0.groovy, service/grails-app/migrations/update-mod-agreements-3-1.groovy, service/grails-app/services/org/olf/EntitlementLogService.groovy, service/grails-app/services/org/olf/ExportService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/grails-app/views/entitlementLogEntry/_entitlementLogEntry.gson, service/src/integration-test/groovy/org/olf/AgreementLifecycleSpec.groovy, service/src/integration-test/groovy/org/olf/AgreementViewsSpec.groovy, service/src/integration-test/groovy/org/olf/TitleServiceSpec.groovy, service/src/integration-test/resources/packages/apa_1062.json, service/src/main/okapi/ModuleDescriptor-template.json, service/src/test/groovy/org/olf/kb/EmbargoSpec.groovy, tools/testing/docker-compose.yml, tools/testing/init.sql
Provide an endpoint to get an event stream of enabled titles
=> Feature - Create entitlement event log

service/grails-app/migrations/update-mod-agreements-3-1.groovy
extended lengths of monograph specific columns in db
=> ERM-1457: Extend length of field for monographVolume, monographEdition, firstAuthor, firstEditor

scripts/enable_kbplus_on_snapshot.sh, scripts/okapi-login, service/grails-app/services/org/olf/KnowledgeBaseCacheService.groovy, service/src/main/groovy/org/olf/kb/KBCacheUpdater.groovy, service/src/main/groovy/org/olf/kb/adapters/EbscoKBAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/GenericRemoteKBAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/KBPlusAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/KIJPFAdapter.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Fix up the KIJPFAdapter - convert it to using the new internal PackageSchema - tested agains KB+ live 24th feb
=> Feature ii kbplus kb

NEWS.md, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-4-0.groovy, service/grails-app/services/org/olf/PeriodService.groovy, service/grails-app/services/org/olf/SubscriptionAgreementCleanupService.groovy
- Changed migration file name
- Added cancellation deadline as saved property on beforeValidate
- Added cancellation deadline to cleanup service
=> ERM-1567: Cancellation deadline doesn't display in Agreements search and sort

service/build.gradle, service/grails-app/conf/logback.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy, service/grails-app/views/object/_object.gson
This reverts commit 38729b502b8fa05bf654677393ef450ca9cb667a.
=> Revert "Feature/tenant name mdc (#407)"

Vagrantfile, service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreement_jobs_simple_search_widget.json, service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreements_simple_search_widget.json
Added Jobs WidgetDef
Updated Agreements WidgetDef
=> ERM-1651/ERM-1652

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreements_simple_search_widget.json
Add renewalPriority as column, sort and filter. Treated as string currently
=> ERM-1730 add renewalPriority to agreements widget defn

service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-5-0.groovy
- add dateCreated, lastUpdated columns to SubscriptionAgreement and Entitlement
- add new migrations file to module-tenant-changelog.groovy
=> ERM-1231 Add date created/last updated metadata to Agreements

service/grails-app/services/org/olf/general/StringTemplatingService.groovy
StringTemplateService will now fire if a StringTemplate has been deleted since the last run
=> fix: Fix for ERM-1777

NEWS.md, service/gradle.properties
NEWS.md updated, SNAPSHOT removed from version
ERM-1865
=> chore: Release 5.0.0

service/grails-app/views/entitlement/_entitlement.gson, service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson, service/src/integration-test/groovy/org/olf/AgreementResourcesViewSpec.groovy
"items" expanded on subscriptionAgreement when not on entitlement controller, and "owner" expanded on entitlement when not on subscription agreement controller
ERM-1891
=> fix: Conditional expansion

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Avoid creating invalid coverage statement when no coverage information is present in GoKB record
ERM-1890
=> feat: ERM-1890

service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
Fix to no longer expand entitlements on a subscriptionAgreement unless the request is coming from the subscriptionAgreementController
ERM-1914
=> fix: Entitlement expansion loop

NEWS.md
Updated NEWS.md file to reflect ERM-1914
=> docs: NEWS.md update

service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-5-1.groovy, service/grails-app/services/org/olf/EntitlementLogService.groovy, service/grails-app/services/org/olf/EntitlementService.groovy, service/grails-app/services/org/olf/ErmResourceService.groovy, service/grails-app/services/org/olf/general/EventListenerService.groovy, service/grails-app/views/entitlementLogEntry/_entitlementLogEntry.gson, service/src/integration-test/groovy/org/olf/EntitlementLogSpec.groovy
Also completes
ERM-1883: Change to coverage should lead to updated entry in EntitlementLog
ERM-1900: Change to suppressFromDiscovery should lead to updated entry in EntitlementLog
=> ERM-1902: Framework for UPDATE entitlement log entry events

NEWS.md, service/gradle.properties, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy
=> Release 5.0.5

service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/controllers/org/olf/general/SettingController.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Exposed AppSettings controller through module descriptor to allow API AppSetting manipulation
ERM-1940
=> feat: AppSettings

service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/domain/org/olf/general/jobs/ResourceRematchJob.groovy, service/grails-app/domain/org/olf/kb/MatchKey.groovy, service/grails-app/migrations/update-mod-agreements-5-1.groovy, service/grails-app/services/org/olf/ErmHousekeepingService.groovy, service/grails-app/services/org/olf/ErmResourceService.groovy, service/grails-app/services/org/olf/KbHarvestService.groovy, service/grails-app/services/org/olf/KbManagementService.groovy, service/grails-app/services/org/olf/MatchKeyService.groovy, service/grails-app/services/org/olf/general/EventListenerService.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy
...no longer runs with all changed TIs in memory
=> ERM-1800: Fixes to rematch process... 

NEWS.md, service/gradle.properties
Updated changelog and removed "-SNAPSHOT" from version number
ERM-2004
=> chore: Release 5.1.0

NEWS.md, service/gradle.properties
Bumped version on master to 5.2.0-SNAPSHOT, added section to changelog
ERM-2004
=> chore: Version bump

service/build.gradle, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-5-2.groovy
Bumped dep on web toolkit to get access to new custprop features: "retired" and LocalDate type properties
refs ERM-778, ERM-2044, ERM-2018
=> feat: Web-Toolkit

service/build.gradle, service/grails-app/migrations/module-tenant-changelog.groovy
Bumped version of web-toolkit so build includes MultiValue custom properties
ERM-2177
=> feat: MultiValue custprops

service/build.gradle
Added immutability to the "value" sets of Multi-Valued CustProps, which enables deletion
ERM-2218
=> feat: MultiValued Custom Properties

service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/dataimport/erm/ErmPackageImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/HeaderImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/PackageSchema.groovy
Added description to packageSchema and related schema files/ingest service logic, so importing packages with a description is now possible
ERM-2219
=> fix: Description

service/grails-app/views/pkg/_pkg.gson, service/grails-app/views/tag/_tag.gson
Some views used g.inline and broke
ERM-2305
=> fix: g.inline

README.md
The lastest in MD Registry is erroneously "mod-agreements-5.3.0-rc.1"
=> Deploy new snapshot ModuleDescriptor

service/gradle.properties
=> chore: Bump the version minor

service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy, service/src/main/okapi/tenant/sample_data/diku-data.groovy
Build availability constraints from gokb feed
ERM-2307
=> feat: Populate availabilityConstraints from GOKb package ingest

service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy
Update PTI url from trusted sources for TI information Also add dev only endpoint to trigger a sync, can access via localhost:8080/admin/triggerSync
ERM-2310
=> feat: PTI url update

scripts/okapi-login, scripts/register_and_enable_rancher.sh, scripts/run_rancher_desktop.sh, scripts/secure_enable.sh, scripts/secure_register.sh, service/grails-app/conf/application-rancher-desktop-db.yml, service/grails-app/conf/logback.groovy
Adds scripts to enable running against a rancher desktop (KInt tooling only at the moment)
=> feat: rancher desktop

service/grails-app/conf/application-rancher-desktop-db.yml
Fixed yml file for rancher desktop
=> fix: Rancher-desktop

NEWS.md, service/gradle.properties
Removed SNAPSHOT and updated NEWS.md file
ERM-2236
=> chore: Release 5.4.0

service/grails-app/controllers/org/olf/ResourceController.groovy
Swapped out the createAlias solution for only displaying TIs with attached PCIs down the line for a nested exists subqueries solution.  Seems to be equally/more performant and solves the issue
ERM-2443
=> fix: Swapped out alias for nested exists subqueries

service/grails-app/controllers/org/olf/ResourceController.groovy, service/src/main/groovy/org/olf/general/Constants.groovy
Use Constants interface to 'nicely' import Query constant 'this' to help mitigate future scenario wherre this needs changing in WeTK
=> refactor: ResourceController

service/grails-app/controllers/org/olf/TitleController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Added new "electronic" endpoint, wired through okapi and ensured parity with functionality of eresources "electronic" endpoint
=> ERM-2510: https://issues.folio.org/browse/ERM-2510

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreement_simple_search_widget_1.2.json
* create new version 1.2 of erm_agreement_simple_search_widget
=> ERM-2629 Add Description filter to Agreements dashboard widget

NEWS.md, service/gradle.properties
Added details to NEWS.md and removed SNAPSHOT from version #
ERM-2492
=> chore: Release 5.5.0

service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
chore: Remove package status handling
Removed status handling for packages in GoKBOAIAdaptor and PackageIngestService (They weren't doing anything anyway)
ERM-2791
=> ERM-2791: Simplification of package status handling

NEWS.md, service/grails-app/domain/org/olf/erm/InternalContact.groovy
* remove defaults in InternalContact class
* update NEWS.md
=> ERM-2885 Reduce number of internal contact role defaults in Agreements

NEWS.md, service/grails-app/controllers/org/olf/PackageController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/src/main/okapi/ModuleDescriptor-template.json
* add fetchSources() method to PackageController
* add sources path to packages collection in UrlMappings
* add /erm/packages/sources entry to ModuleDescriptor-template
* edit NEWS.md
=> ERM-2925 Add backend support for retrieving list of source values

service/grails-app/domain/org/olf/kb/CoverageStatement.groovy, service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/ErmResourceService.groovy, service/grails-app/services/org/olf/general/EventListenerService.groovy
Reverts folio-org/mod-agreements#660
=> Revert "ERM-2923 Add created/updated metadata for Resources in local KB"

service/grails-app/domain/org/olf/kb/ErmResource.groovy, service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/general/EventListenerService.groovy
Reverts folio-org/mod-agreements#663
=> Revert "ERM-2393: Move session update event listener out of beforeValidate"

service/grails-app/migrations/docs.groovy
* add modifyDataType changeSet to docs.groovy migrations
=> ERM-2961 Extend length of document URL to 2048 chars

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreement_simple_search_widget_1.3.json
* create erm_agreement_simple_search_widget version 1.3
* add alternateName string filter
* add alternateNames array filter
=> ERM-2628 Add Alternative Name filter to Agreements dashboard widget

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreement_lines_simple_search_widgets.json
Changed value type for last updated from datetime to date to resolve errors
[ERM-2934](https://issues.folio.org/browse/ERM-2934)
=> ERM-2934: Agreement line widget date fix

service/grails-app/conf/spring/resources.groovy
Swap IngressType to pushKB temporarily for QA purposes
ERM-2630
=> feat: Switch to pushKB

service/grails-app/conf/spring/resources.groovy
Turned harvest mode back on, turned off pushKB mode
=> chore: Harvest mode

service/build.gradle
=> fix: No session downloading stream

service/grails-app/conf/spring/resources.groovy
Swapped back to IdFirstTIRS, ready for release
=> chore: IdFirstTIRS

NEWS.md, service/gradle.properties
Added details to NEWS.md and removed SNAPSHOT from version #
ERM-2650
=> chore: Release 6.0.0

service/grails-app/migrations/update-mod-agreements-6-0.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy
chore: Added preconditions to each index creation in order to protect against systems where such indices had been added manually
refs ERM-3064
=> ERM-3064: Add preconditions to index creation

service/grails-app/conf/logback-development.xml, service/grails-app/conf/logback.xml
chore: Logging
Tweak logging output for TitleInstanceResolverServices, now include DEBUG level info on sys out, and attach error/info messages to job logs as expected
ERM-3087
=> ERM-3087: Add debug message to indicate ingest mode

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreement_simple_search_widget_1.4.json
* create erm_agreement_simple_search_widget_1.4.json
* add contentTypes and hasContentTypes filters
=> ERM-3120 Add Content type filter to Agreements dashboard widget

service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy, service/src/main/groovy/org/olf/kb/adapters/WebSourceAdapter.groovy
* add User-Agent header
* fix JobRunnerService
=> ERM-3127 Use clearly identifiable user-agent for requests to GOKb

service/grails-app/migrations/update-mod-agreements-6-0.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy
Reverts folio-org/mod-agreements#717
=> Revert "Feat/proposed quesnalia improvements"

service/src/main/okapi/tenant/sample_data/_data.groovy
Swap to harvesting from GOKb_TEST for the time being
=> chore: GOKb_TEST

service/src/main/okapi/tenant/sample_data/diku-data.groovy
Revert diku data back to ensure full GOKB Ingest again
=> chore: Diku data

NEWS.md
=> docs: Include patch release notes on master branch

NEWS.md
Added NEWS.md section to reflect changes made in 7.0.2 release
=> docs: Post patch release

service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy
Refactor code responsible for clearing job allocation of "Queued" jobs from dead runners into separate Transactional method. This reflects the interruptJob logic which was working fine.
Module can now recover from multiple restarts, including during federated lock tenant seeding, seemingly fine without locking up database connections at all
Also added tenant information to zombie job logging
=> fix: Refactor clearJobAllocation

NEWS.md, service/gradle.properties, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy
Added NEWS.md section and bumped version -> 7.0.3
=> chore: Release 7.0.3

NEWS.md, service/gradle.properties, service/grails-app/conf/application-dc.yml, tools/testing/init.sql
Fixed grails version pulling in databinding library with security issue.
Included application-dc profile yaml and changes to init.sql to allow its use
=> chore: Release 6.1.2

NEWS.md
Updated NEWS.md file to reflect patch 7.0.4
=> docs: Post patch doc update

NEWS.md, service/gradle.properties, service/grails-app/conf/application-dc.yml
build: Poppy: grails 5.3.6 fixing databinding DoS (CVE-2023-46131)
Fixed grails version pulling in databinding library with security issue. Included application-dc profile yaml
ERM-3138
=> Release 6.0.3

NEWS.md, service/gradle.properties, service/grails-app/controllers/org/olf/TitleController.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/TitleFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy
GBV specific release containing fixes for ERM-3166 and ERM-3185. Left in draft for now while we ensure Poppy-main branch is as expected
=> Release 6.1.3

service/grails-app/controllers/org/olf/ResourceController.groovy, service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/views/resource/staticEntitlementOptions.gson, service/src/main/okapi/ModuleDescriptor-template.json
Added new endpoint for entitlementOptions which is _significantly_ faster than the old one
refs ERM-3246
=> feat: /static/entitlementOptions

NEWS.md, service/gradle.properties, service/grails-app/conf/logback-development.xml, service/grails-app/services/org/olf/TitleEnricherService.groovy, service/grails-app/services/org/olf/TitleIngestService.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy, service/src/main/okapi/ModuleDescriptor-template.json, service/src/main/okapi/tenant/sample_data/_data.groovy
Added NEWS.md section and bumped version -> 7.0.6
- ERM-3291 Fix permissions on /erm/validate/remoteKB in mod-agreements
- ERM-3289 Fix permission on /erm/validate/subscriptionAgreement in mod-agreements
- ERM-3288 Fix permission on /erm/files/{id}/raw in mod-agreements
- ERM-3274 If a citation gets passed to BaseTIRS without an instancePublicationMedia field it will crash
- ERM-3254 With WorkSourceIDTIRS for GOKb we see "Field error in object" errors
=> Release 7.0.6

NEWS.md
Added NEWS.md section from 7.0.6 release
=> chore: Post release 7.0.6

.github/workflows/run-int-tests.yml
swap docker-compose for docker compose
=> ci: Tweak int tests action to ensure they run on PRs properly

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
OKbOAIAdapter -> GOKbOAIAdapter
=> Correct typo in log message

service/src/main/okapi/tenant/sample_data/diku-data.groovy
chore: Swap from GOKb_TEST to GOKb remoteKB for testing full ingest speeds with changes to coverage stuff
=> chore: Swap from GOKb_TEST to GOKb

service/src/main/okapi/tenant/sample_data/diku-data.groovy
Switch back to test ingest for snapshot builds
=> chore: GoKB Test

NEWS.md, service/src/main/okapi/tenant/sample_data/_data.groovy
Tweak to disable Gokb harvest by default in sample data, added note to devs to avoid changing this file on master for the time being
=> feat: Sample data tweak

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
fix: Open ended coverage
Previously accidentally added an if statement which would reject open ended coverage statements out of hand
ERM-3330
=> ERM-3330: Open ended coverage statements not ingested from GOKb

NEWS.md, service/gradle.properties, service/grails-app/migrations/correct-gin-indices-pre-poppy.groovy, service/grails-app/migrations/correct-gin-indices-pre-quesnalia.groovy, service/grails-app/migrations/module-tenant-changelog.groovy
NOT to be merged yet, looks like there are some changes around coverage that may also need to go into this release
=> Release 6.1.8

NEWS.md, service/gradle.properties, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy
GBV Poppy compatible release - refs ERM-3364
=> Release 6.1.9

NEWS.md
Include NEWS.md section from 7.0.9 in main release line
=> chore: Post release

NEWS.md, service/gradle.properties, service/src/main/okapi/ModuleDescriptor-template.json
Added news sections and incremented version
=> Release 7.1.1

NEWS.md
Updated NEWS for 7.1.1
ERM-3440
=> chore: Post release 7.1.1

NEWS.md, service/gradle.properties, service/grails-app/services/org/olf/DependentModuleProxyService.groovy, service/grails-app/services/org/olf/general/pushKB/PushKBService.groovy
Added NEWS section and bumped version to 7.1.2
ERM-3456
=> Release 7.1.2

NEWS.md
Added NEWS section reflected in release 7.1.2
=> chore: Post-release 7.1.2

NEWS.md
Fixing some small oversights from releases
=> docs: Added missing dates to changelog sections

NEWS.md
Added NEWS section reflected in release 7.1.3
=> chore: Post-release 7.1.3

NEWS.md
Added NEWS.md section reflected in 7.1.5 release
=> chore: Post release 7.1.5

NEWS.md
=> docs: Added env variable changes to changelog

NEWS.md, service/gradle.properties, service/grails-app/conf/application-dc.yml, service/grails-app/conf/application-rancher-desktop-db.yml, service/grails-app/domain/org/olf/kb/Identifier.groovy, service/grails-app/services/org/olf/IdentifierService.groovy, service/src/integration-test/groovy/org/olf/AgreementLifecycleSpec.groovy, service/src/integration-test/groovy/org/olf/BaseSpec.groovy, service/src/integration-test/groovy/org/olf/IdentifierServiceSpec.groovy, service/src/integration-test/groovy/org/olf/PlatformSpec.groovy, service/src/integration-test/groovy/org/olf/StringTemplateBulkSpec.groovy, service/src/integration-test/groovy/org/olf/TIRS/IdFirstTIRS/IdFirstTIRSSpec.groovy, service/src/integration-test/groovy/org/olf/TIRS/TIRSSpec.groovy, service/src/integration-test/groovy/org/olf/TitleServiceSpec.groovy, service/src/integration-test/resources/packages/idFirstTIRS/citations/fix_equivalent_ids.json, service/src/integration-test/resources/packages/idFirstTIRS/citations/fix_equivalent_ids_2.json, service/src/integration-test/resources/packages/idFirstTIRS/citations/fix_equivalent_ids_3.json, service/src/integration-test/resources/packages/idFirstTIRS/ifitirs_pkg.json, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/TitleFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy, service/src/main/groovy/org/olf/kb/IdentifierException.groovy
ERM-3281: Design and implement process to resolve eissn, pissn, eisbn and pisbn namespaces (#792)
DO NOT MERGE
=> chore: Release 7.0.11

service/src/main/okapi/tenant/sample_data/diku-data.groovy
Set GOKBT remoteKB to active.FALSE
=> Turn off harvest for diku-data.groovy

NEWS.md, service/gradle.properties
Updated NEWS.md, bumped version -> 7.2.0
ERM-3401
=> chore: Release 7.2.0

NEWS.md, service/gradle.properties
Added NEWS.md section, bumped appVersion -> 7.3.0-SNAPSHOT, bumped okapiInterfaceVersion -> 7.3
=> chore: Post release 7.2.0

NEWS.md
Added NEWS.md section reflected in 7.2.1 release
=> chore: Post release 7.2.1

service/grails-app/conf/application.yml
* add empty string fallback to application.yml
=> ERM-3658 S3 secret key in Agreements and licenses app settings is pre-populated incorrectly

NEWS.md
Added NEWS.md section reflected in 7.2.2 release
=> docs: Post release 7.2.2

service/grails-app/controllers/org/olf/StatisticsController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Also added endpoint to ModuleDescriptor and included permissions along with "agreements view"
=> feat: Added statistics controller, along with kbCount and sasCount endpoints

service/grails-app/migrations/add-missing-primary-keys-for-trillium.groovy, service/src/integration-test/groovy/org/olf/PrimaryKeySpec.groovy
Also added the tag tables to the exclusions in PrimaryKeySpec
refs ERM-3796
=> fix: Remove PKs from tag tables -- ERM-3796

service/src/main/okapi/ModuleDescriptor-template.json
This will be surfaced to the user via the UI perms
=> Hide BE permission from view
