folio-org/mod-agreements

scripts/dev_submit_pkg.sh, service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/src/main/groovy/org/olf/kb/adapters/EbscoKBAdapter.groovy
This PR enables mod-erm to import packages from EBSCO KB. This works by allowing the system to declare a RemoteKB record for EBSCO -- this is tested in dev_submit_pkg.sh with 
RS_EBSCO_ID=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/kbs -d '
{
name:"EBSCO",
type:"org.olf.kb.adapters.EbscoKBAdapter",
cursor:null,
uri:"https://sandbox.ebsco.io",
listPrefix:null,
principal:"'"$EBSCO_SANDBOX_CLIENT_ID"'",
credentials:"'"$EBSCO_SANDBOX_API_KEY"'",
rectype:"1",
active:false,
supportsHarvesting:false
}
'`
Things to note here: the EBSCO implementation does not support harvesting, the dev_submit_pkg.sh file now calls out to a file in the user home directory called folio_privates.sh. Developers wanting to use this functionality will …
=> Initial Work - Integrate with EBSCO KB

service/grails-app/services/org/olf/CoverageExtenderService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy
Tighten up the rules on coverage overlap detection and when to use a fuzzy match after an identifier match fails.
=> Improve package ingest - coverage overlap detection and fuzzy match threshold

scripts/eresources.sh, service/grails-app/domain/org/olf/general/Org.groovy, service/grails-app/domain/org/olf/kb/ContentActivationRecord.groovy, service/grails-app/migrations/initial-model.groovy, service/grails-app/services/org/olf/KnowledgeBaseCacheService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy
Add org.reference as a general field which is temporarily being used to hold EKB vendor.id when wanting to do content activation in EKB. Expect this to be moved to a custom property like EKBVendorId in the near future, but reference a perfectly good temporary holding position.
=> Add reference or Org (proxy for vendor)

service/settings.gradle
Ensure gradle property appName is honoured and can therefore be overridden at build time.
=> project name should be set from the property appName.

Jenkinsfile, service/build.gradle, service/src/main/okapi/ModuleDescriptor-template.json
* Added custom Jenkinsfile for FOLIO CI
* Don't covert docker image name to lower case.   The 'id' field in the module descriptor needs to match the docker image name (and case). 
* Add a launch descriptor to the module descriptor template.  This is needed for deployment to FOLIO testing environment. 
TODO in a future PR.   Add ability to provision an Okapi and Postgres instance during the build to run the integration tests.
=> All mod-erm to FOLIO CI

service/build.gradle, service/src/main/okapi/ModuleDescriptor-template.json
The interface name and interface version specified in the module descriptor should be distinct from the module name and version.    An interface can be independent of a module .  Also, I don't think you want to increment the interface version each time a new version of the module is released (snapshot or release version).  Probably should only be changed when the interface has changed.
=> update interface name and version

scripts/dev_submit_pkg.sh, service/grails-app/domain/org/olf/erm/SAOrg.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/migrations/initial-model.groovy
PR adds the ability to store a license ID and a collection of arbitrary orgs with an associated role to subscription agreements. See dev_submit_pkg.sh for an example of how this works, but you can now post
TRIAL_AGREEMENT_ID=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/sas -d '
{
name: "Trial Agreement LR 001",
description: "This is a trial agreement",
agreementStatus: { id: "'"$STATUS_DRAFT_RDV"'" },
isPerpetual: { id: "'"$ISPERPETUAL_YES_RDV"'" },
renewalPriority: { id: "'"$RENEW_REVIEW_RDV"'" },
localReference: "TRIAL_ALR_001",
vendorReference: "TRIAL_AVR_001",
attachedLicenceId: "UUID_OF_LICENSE_TO_LINK",
startDate: "2018-01-01",
endDate: "2018-12-31",
renewalDate: "2019-01-01",
nextReviewDate: "2018-10-01",
vendor: { …
=> Add license and orgs to subscription agreement

service/src/main/okapi/ModuleDescriptor-template.json
Gonna need this (or something like it) for [UIER-23](https://issues.folio.org/browse/UIER-23) so that users can select existing orgs.
=> Added /erm/org route to ModuleDescriptor

service/src/main/okapi/ModuleDescriptor-template.json
Necessary for [UIER-23](https://issues.folio.org/browse/UIER-23).
The combined combobox approach is a problem due to the issues associated with agreement `orgs` either being specified by a string (if passing an ID) or an object (when passing a name to create an org with). Switching to a two-stage process with a separate "Create Organization" step solves that issue.
Additionally, it'll allow us to immediately verify that an org with a given name doesn't already exist and perform the vendors cross-referencing at the same time. It also _heavily_ cleans up the code.
=> Added POST route for Orgs

service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
Was having the same issue as with deletes for the entitlements array where the original response from the PUT was correct but subsequent GETs on the resource weren't. Per convo with @ianibbo, not sure if we're gonna continue with the `_delete` flags for this but figured I'd get this fix in so that the end-to-end system works as expected until we figure out a plan going forward.
=> Turned on cascading for SA org deletions

service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
AFAIK this shouldn't be a gigantic array. Expanding it would be a big help in cleaning up the front-end code since we _already_ have to go out to fetch the user info from `/users`.
On a related note, is it possible to have separate expansion rules for when we fetch a list of resources vs a single one? E.g., fetching fewer fields when getting `/erm/sas` than `/erm/sas/1234`?
=> SubscriptionAgreement: Expand internal contacts

scripts/dev_submit_pkg.sh, scripts/eholdings/create_agreement.sh, service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/grails-app/domain/org/olf/kb/ErmResource.groovy, service/grails-app/domain/org/olf/kb/RemoteKB.groovy, service/grails-app/migrations/initial-model.groovy, service/grails-app/services/org/olf/ErmHousekeepingService.groovy, service/grails-app/services/org/olf/KbHarvestService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy, service/src/main/okapi/ModuleDescriptor-template.json
In preparation for eholdings intergation, make entitlements able to represent packages defined in external systems as well as the internal KB domain model. Added a script that demonstrates the kind of conversation that might take place between eholdings and agreements when creating agreements, and adding entitlements that refer to packages in EKB.
=> Make entitlements able to refer to external resources

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Force the timezone to Z in the output format, and make sure that the values are created using a UTC time zone. For compliance with OAI-PMH.
=> Force timezone in OAI from params

service/src/main/okapi/ModuleDescriptor-template.json
The "Memory" property belongs inside the "HostConfig" object.
See documentation linked from [FOLIO-2235](https://issues.folio.org/browse/FOLIO-2235).
Compare with other back-end modules.
=> FOLIO-2235 Fix misplaced launchDescriptor Memory setting

service/gradle.properties, service/grails-app/controllers/org/olf/PackageController.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Small tweaks to mod-agreements including:
- Changes to import services to pass package ids through to the import endpoint
- package  import endpoint now returns package id
- package import endpoint now exposed
=> ERM-700, ERM-702 and ERM-737: Changes to allow LAS:eR import

service/grails-app/controllers/org/olf/PackageController.groovy, service/grails-app/domain/org/olf/general/jobs/KbartImportJob.groovy, service/grails-app/services/org/olf/ImportService.groovy
- Switched csvReader usage to take into account tabs as separator, ignore quotes when used
- Cleanup of endpoint render method
- Changed coverage and identifier building methods, now they're validated before deciding whether or not to add them to the package resource
- Other miscellaneous cleanup
=> ERM-769: Fix to import of KBART files

service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/controllers/org/olf/PackageController.groovy, service/grails-app/domain/org/olf/general/jobs/KbartImportJob.groovy, service/grails-app/domain/org/olf/kb/RemoteKB.groovy, service/grails-app/migrations/update-mod-agreements-2-3.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/KnowledgeBaseCacheService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/src/main/groovy/org/olf/dataimport/erm/ErmPackageImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/HeaderImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/PackageSchema.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy, service/src/main/okapi/tenant/sample_data/diku-data.groovy
This PR creates a `trustedSourceTI` tag on both `RemoteKB`s and `KbartJobs`, as well as extending the JSON schema to allow them to be set there.
- A trusted tag set to true on an import job means that that import will be allowed to overwrite selected title metadata, and visa versa for false.
- An import without this tag will defer to the LOCAL remoteKB object's setting (And if it cannot find this then `false`)
=> ERM-793, ERM-794, ERM-795: Allowing for setting of a "Trusted source for title instance metadata" tag

service/grails-app/services/org/olf/PackageIngestService.groovy
- Added a check to see if the package status is null, defaulting to allow import in this case.
- Case insensitivity added to the checks for "current" and "expected"
=> ERM-839: Fixed bug preventing file imports

service/grails-app/services/org/olf/ImportService.groovy
We were previously getting an unexpected match on empty coverage data in monographs, so I've tweaked the code to use `trim()` and check both for null and empty string values.
=> ERM-866 Tweaked coverage date checking

Vagrantfile, service/grails-app/domain/org/olf/erm/Entitlement.groovy
We now accept enough data to output the following objects.
For a package:
```
{
"label": "EBSCO eBooks",
"type": "Package",
"provider": "EBSCO",
"titleCount": 1902197,
"selectedCount": 1902193,
"contentType": "E-Book",
"providerName": "EBSCO",
"isSelected": true,
"accessStatusType": "Trial"
}
```
For a title:
```
{
"label": "Alice in Wonderland and Through the Looking Glass",
"type": "Book",
"provider": "EBSCO",
"publicationType": "Book",
"identifiers": [
{
"id": "978-1-84002-256-8",
"type": "ISBN (Print)"
},
{
"id": "978-1-84943-747-9",
"type": "ISBN (Online)"
}
],
"authors": [
"Lewis Carroll"
],
"editors": [
"An Editor"
],
"packageData": {
"name": "EBSCO eBooks",
"titleCount": 1902197,
"selectedCount": 1902193,
"contentType": "E-Book",
"providerName": "EBSCO",
"isSelected": true
}, …
```
=> ERM-874: Expanded fields we accept from eHoldings entitlement API Call

service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/domain/org/olf/erm/AgreementRelationship.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/i18n/messages.properties, service/grails-app/migrations/update-mod-agreements-2-3.groovy, service/src/main/okapi/ModuleDescriptor-template.json
- Added uniqueness validation to Agreement names
- exposed validation endpoints through Okapi
- added i18n message for non-unique agreement names
- migrations to append integers to existing non-unique names so A, A, A becomes A_1, A_2, A_3
=> Inline validation updates

service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/controllers/org/olf/ValidateController.groovy, service/grails-app/domain/org/olf/erm/AgreementRelationship.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/i18n/messages.properties, service/grails-app/migrations/update-mod-agreements-2-3.groovy, service/grails-app/views/errors/_errors.gson, service/src/main/okapi/ModuleDescriptor-template.json
This PR adds the validation endpoints previously set up by Steve, a uniqueness constraint on agreement names and migrations for existing non-unique names. 
Also exposed the new endpoints and added an i18n message for non-unique agreement names.
=> ERM-891: Feature/inline validation, Require agreement names to be unique

service/grails-app/services/org/olf/KbHarvestService.groovy
Not needed as check for pending jobs runs on a scheduled basis
=> ERM-941 Remove time condition when looking for pending jobs

service/grails-app/controllers/org/olf/ExportController.groovy, service/grails-app/services/org/olf/ExportService.groovy, service/grails-app/views/export/_exportEntry.gson
For each resource under "resources" on an agreement export, there is now an "agreementLine" section, containing the entitlement id, suppressFromDiscovery flag and any tags on that entitlement.
In addition, tags on the TI, PCI or PTI will now show up in the export, and a bug was fixed where the entitlement information was not grabbed in the PTI resource case.
=> ERM-925, ERM-929, ERM-930, ERM-931: AgreementLine info and tags added to export

service/grails-app/views/export/_exportEntry.gson
Slight fix for change merged. I had missed a couple of places where the suppressFromDiscovery flag needed to be, and added it to the TI where it is currently unnecessary and confusing.
=> ERM-930: Removed suppressFromDiscovery from TI level, added to PCI/PTI level

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Avoids unnecessary parsing of each TIPP in packages that will not be ingested and reduces the number of info log messages (on initial GOKb harvest from test system the number of info log messages is over half the number)
=> ERM-995: Check package, list and edit status before parsing full package content

service/grails-app/services/org/olf/ImportService.groovy
The KBART import could get stuck in a loop - this stops that happening
=> ERM-993 Ensure import moves to next line if no publication_type

service/grails-app/views/comparison/compare.gson
A couple of tweaks to the comparison output view, one to bring the embargo units in line with elsewhere for 996, and one to add PTI longName and name properties for 1013
=> ERM-996, ERM-1013: Changed embargo units in comparison output, added longName and name to PTI

service/grails-app/domain/org/olf/kb/ErmResource.groovy, service/grails-app/domain/org/olf/kb/TitleInstance.groovy, service/grails-app/migrations/update-mod-agreements-2-4.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/TitleEnricherService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/grails-app/views/ermResource/_ermResource.gson, service/grails-app/views/titleInstance/_titleInstance.gson, service/src/main/groovy/org/olf/kb/KBCacheUpdater.groovy, service/src/main/groovy/org/olf/kb/adapters/EbscoKBAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/GenericRemoteKBAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/KBPlusAdapter.groovy, service/src/main/groovy/org/olf/kb/adapters/KIJPFAdapter.groovy
- add publicationType refdata property to TitleInstance and ErmResource
- migrate type values to publicationType values in erm_resource
- change existing type values in erm_resource
- delete refdataValues for TitleInstance.type
- add publicationType to ermResource and titleInstance template
- add publication_type to kb adapters
- update import, title services
- refs ERM-984, ERM-986, ERM-987, ERM-988
=> ERM-943 Separate ERM 'publication type' from 'type'

service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy
Small syntax and formatting tweaks, appear to have fixed the issue.
=> ERM-1006: Fix for "Future" and "Dropped" title lists from directly linked PCIs

service/grails-app/services/org/olf/ComparisonService.groovy
Now sorts by ti.id after ti.name in order to reflect the tweaks made to comparison output. Should hopefully stop instances where merging doesn't occur.
=> ERM-994: Slightly tweaked SQL to reflect name+id sorting

service/grails-app/views/comparison/compare.gson
Embargo output didn't match embargo output elsewhere, which was causing proptype warnings in the frontend. This PR brings the embargo lengths into line with the way we render them elsewhere, as numbers instead of strings.
=> Switched embargo moving wall start/end lengths from strings to numbers

service/grails-app/domain/org/olf/erm/Entitlement.groovy
Changed beforeValidate to check 'not internal' rather than 'is external'.
This approach taken to expand on existing behaviour now we have more than two types.
=> ERM-1083: Ensure that Entitlements that are not related to an internal KB resource cannot have custom coverage saved

service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy, service/src/main/groovy/org/olf/dataimport/erm/ContentItem.groovy, service/src/main/groovy/org/olf/dataimport/erm/TitleInstance.groovy, service/src/main/groovy/org/olf/dataimport/internal/PackageContentImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/PackageSchema.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
This also references ERM-987.
Moved a bunch of code around--most notably the logic which "guesses" the type from import, which is now in adapter. Anything coming in through internal routes (Import/KBART import) should already have a valid type--if it doesn't it gets rejected.
A few other tweaks, including one to fix the behaviour of the enrichment process... refdata fields did not seem to dirty the title, causing failure to save unless alongside a String field. (Workaround now in place), and some error message tweaks as well.
=> ERM-986: Update data import process to handle new publicationType property.

service/src/main/groovy/org/olf/export/KBart.groovy
As the title mentions, hard-coded KBART header fields in, rather than relying on public/private declared fields
=> ERM-1140 KBART export omits column headers/field names: Hard coded KBART fields

service/grails-app/services/org/olf/EntitlementLogService.groovy, service/grails-app/services/org/olf/ExportService.groovy
- Changes appear to have been made to the way Hibernate builds its queries, meaning we've had to move some conditions out of the WHERE and into the JOIN, replacing the WHERE conditions with not-null constraints.
=> ERM-1203: Changes to HQL query in exportService

service/grails-app/views/entitlement/_externalEntitlement.gson
Changed how we expand the owner of external entitlements outside of subscription agreement calls
=> ERM-1238: /erm/entitlements endpoint doesn't expand owner when entitlement is external

service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy, service/grails-app/migrations/update-mod-agreements-3-1.groovy, service/grails-app/services/org/olf/ErmHousekeepingService.groovy, service/grails-app/services/org/olf/PeriodService.groovy, service/grails-app/services/org/olf/SubscriptionAgreementCleanupService.groovy, service/src/main/okapi/ModuleDescriptor-template.json
Agreement start/end dates now saved to db - refs ERM-1532
OnValidate they are recalculated to be the earliest period start and latet period end, respectively
ERM admin endpoint now exposed, with new perm `erm.admin.action`.
Housekeeping task replaces old entitlement log update timer task. Now 3 housekeeping tasks will run on a 24 hour basis, including the entitlement log timer task and the new date cleanup task
Date cleanup task will fetch agreements, and compare their stored start/end dates to the periods. Discrepancies are then fixed. (This replaces a traditional migration between versions--allows for sweeping up of invalid data on a daily basis, so Agreement dates should never get out of date for more than a day)
=> ERM-1533: Agreement start and end dates should be the earliest period start and latest period end date respectively

service/build.gradle
This fixes Machine-in-the-Middle (MITM) attack vulnerabilities,
for details see
https://issues.folio.org/browse/FOLIO-3106
https://issues.folio.org/browse/FOLIO-3044
https://issues.folio.org/browse/FOLIO-3045
=> FOLIO-3106: Use https for maven repositories

service/build.gradle
Replace http by https for maven.k-int.com, fixing MitM vulnerability.
Unencrypted http allows an attacker to run a
Machine-in-the-Middle (MitM) attack that replaces
the content downloaded during the build by malware.
Such attacks against unencrypted maven repositories are well-known since 2019:
https://github.com/github/securitylab/issues/21
For this reason maven disabled unencrypted http by default since 2021:
https://maven.apache.org/docs/3.8.1/release-notes.html#cve-2021-26291
=> FOLIO-3131: Use https for maven.k-int.com

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Feedback from GOKb indicates that only packages with editStatus == rejected should be skipped during harvesting and that other statuses (approved, in-progress) should be treated as good to harvest
=> Change editStatus logic on harvesting from GOKb

service/grails-app/services/org/olf/ErmHousekeepingService.groovy, service/grails-app/services/org/olf/SubscriptionAgreementCleanupService.groovy
Added triggerOrgsCleanup method to SubscriptionAgreementCleanupService, which will delete any Org records not in use either on a SubscriptionAgreementOrg or a Pkg
=> feat: ERM-1774 Regularly remove organizations that do not have any links to Agreements/Packages

service/grails-app/domain/org/olf/kb/ErmResource.groovy
Error on adding coverage to PCI which overlaps with existing coverage on PTI/TI, validate now uses existing session
=> fix: ERM-1781

service/grails-app/services/org/olf/TitleInstanceResolverService.groovy
Namespace mapping was not occurring in a vital place, this has been rectified to stop us creating multiples of the same identifier (eissn AND issn for example) and then matching on them as if they were the same, giving us a double match and a failure.
ERM-1847 - This will stop the data problem which causes that crash. Separate work done to ensure no crash in this case in future
=> fix: namespace mapping fix ERM-1649

service/grails-app/services/org/olf/TitleIngestService.groovy, service/grails-app/services/org/olf/TitleInstanceResolverService.groovy
ERM-1847: Failure to resolve a title should lead to skipping title
Changed an assert to instead throw an exception, to stop job hanging
ERM-1847
=> fix: ERM-1847

service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy, service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
customProperties now clonable with the key 'supplementaryProperties', and the key for 'supplementaryDocs' has been changed from 'supplementaryInformation' to 'supplementaryDocs' pending frontend work
ERM-1848
=> feat: Allow cloning supplementaryProperties

service/grails-app/views/entitlement/_entitlement.gson
On editing an agreement with an agreement line for a PCI, "custom coverage" incorrectly populated. We now only render default coverage as 'coverage' when not on the subscription agreement controller
ERM-1903
=> fix: ERM-1903

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy
Changed match logic so that any title instances currently in system with identifiers of type eissn or pissn or the like are matchable against incoming versions of the identifier of type issn etc. Also added a comment to the effect that this is temporary, when we eventually have a fix for the databases we wouldn't expect to have to match against any eissn etc in the DB
ERM-1917
=> fix: Namespace mapping

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/export/KBart.groovy
Allowed incoming issn to match to existing eissn in DB, same for isbn and print versions etc. Also allowed eissn values in DB to show up on KBART export
=> fix: Identifier mapping

service/build.gradle
Fix to update to latest version of web-toolkit. Fix was to remove caching of domainUtil properties... certain fields were being marked initially as "non-sortable" because they were first accessed through a non sortable property, such as "some.unsortable.property.something.child". Then when another process attempted to access "child", it would be marked as unsortable in the cache, stopping the sort. Caching has now been removed
ERM-1931
=> fix: Sort agreement lines by name then reference then UUID in the UI

service/grails-app/controllers/org/olf/AdminController.groovy, service/grails-app/controllers/org/olf/general/jobs/PersistentJobController.groovy, service/grails-app/domain/org/olf/general/jobs/NaiveMatchKeyAssignmentJob.groovy, service/grails-app/migrations/update-mod-agreements-5-1.groovy, service/grails-app/services/org/olf/MatchKeyService.groovy, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy, service/grails-app/views/naiveMatchKeyAssignmentJob/_naiveMatchKeyAssignmentJob.gson
Added a new kind of job, "NaiveMatchKeyAssignmentJob". The only entry point for creating this job is through the admin endpoint. On creation, this job will go through each PCI in the system which does not have matchKeys and attempt to naively assign them from the internal data. This will simply proliferate all errors inherent in data and can take a VERY long time if run on a system with no match keys and many PCIs, so should not be run very often
ERM-1799
=> feat: NaiveMatchKeyAssignmentJob

service/grails-app/domain/org/olf/kb/MatchKey.groovy, service/grails-app/services/org/olf/ErmResourceService.groovy, service/grails-app/services/org/olf/MatchKeyService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/grails-app/services/org/olf/general/EventListenerService.groovy
UpsertMatchKeys replaced with updateMatchKeys, which checks each match key on resource against incoming matchKeys, and can insert or remove those key/value pairs which are not equivalent. Also added a toString for MatchKeys, and updated eventHandler to kick off ResourceRematch when match keys change. This will cause ResourceRematch on TI creation.
=> fix: MatchKey

service/grails-app/domain/org/olf/general/jobs/ResourceRematchJob.groovy, service/grails-app/services/org/olf/KbManagementService.groovy, service/grails-app/services/org/olf/MatchKeyService.groovy, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy
Disables Automatic rematch process
Fixes some MatchKey -> schema generation issues
Changes (behind disabled work) to improve the "count" performance for automatic rematching
Adds method to trigger rematch for limited list of jobs, via ResourceRematch `payload` field.
Adds error message to "Job execution failed" job log entry, to provide slightly more information to user.
=> fix: ERM-1800

service/grails-app/views/entitlement/_entitlement.gson
Removed explicit suppressFromDiscovery key from view file to ensure we don't get duplicate keys
ERM-2001
=> fix: Duplicate key

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_agreement_simple_search_widget_1.1.json
Removed != option for ogranizations array due to how that works for arrays in web-toolkit
ERM-2036
=> fix: Removed isNot

service/grails-app/controllers/org/olf/UrlMappings.groovy
Removed default perPage 100 in urlMappings (It didn't work consistently anyway)
=> chore: UrlMappings

service/grails-app/views/pkg/_pkg.gson
Pkg view file had a manual identifiers expansion but failed to exclude the built in identifiers render, resulting in two "identifiers" keys in the resulting JSON, rendering it invalid
ERM-2174
=> fix: Pkg view had duplicate "identifiers" expansion

service/grails-app/domain/org/olf/kb/ErmResource.groovy
Identifiers obtained via `getApprovedIdentifierOccurrences` are now sorted by default, first by namespace, then by value.
This leads to a stable representation in the UI where we have multiple identifiers within a single namespace
ERM-946
=> feat: Sort Identifiers

service/gradle.properties
The lastest in MD Registry is erroneously "mod-agreements-5.3.0-rc.1"
=> Deploy new snapshot ModuleDescriptor as v5.3.1

service/build.gradle
Also re-enable the gradle artefact cache use for the build.
=> fix: Bump toolkit for datastore properties fix

service/grails-app/services/org/olf/PackageIngestService.groovy
Ensure on creation, refdata is only created via its `lookupOrCreate` domain method.
ERM-2367
=> fix: Refdata binding

service/grails-app/services/org/olf/PackageIngestService.groovy
fix: String parsing
Accidentally tried to parse String as if it were Refdata
ERM-2288
=> ERM-2288: On updating an existing package in Agreements local KB, update/overwrite existing package metadata

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
feat: Secondary Enrichment
Turned off secondary enrichment call for titles ingested through the GoKB OAI feed, hopefully improving performance. The data is now available directly from within the `TIPP.title` section of the main feed.
ERM-2370
=> ERM-2370: Extend GOKb harvest to include new monograph metadata fields and stop using secondary lookup

service/grails-app/domain/org/olf/kb/ContentType.groovy
chore: Removed ContentType defaults
Content types are set via the ingest process and we do not perform logic on them, so we have no need to bootstrap them
ERM-2378
=> ERM-2378: Remove defaults from ContentType

service/grails-app/views/entitlement/_externalEntitlement.gson, service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
External entitlements no longer fetch resource on `index` action. In addition, subscriptionAgreement now accepts queryParam `excludes` to allow selective exclude from the query itself
ERM-2423
=> fix: ExternalEntitlements

service/grails-app/views/entitlement/_externalEntitlement.gson
Added a queryParam to quash the fetching of external resources. It's a little clunky because it needed to keep backwards compatibility, but there may be a rewrite of this stuff in Orchid and beyond, so for Nolana bugfix it's the most expedient thing to do
ERM-2423
=> fix: fetchExternalResources

service/grails-app/services/org/olf/general/StringTemplatingService.groovy
chore: Tweak to lock name
Tiny tweak to fix typo in lock name, and move things around a bit
ERM-2469
=> ERM-2469: HibernateException: Duplicate identifier in table for AppSetting

service/grails-app/services/org/olf/PackageIngestService.groovy
fix: Added null safety
In a couple of instances, fields were set to refdata using "____FromString". When that string is not present, or is `null`, this causes an exception to be thrown
ERM-2475
=> ERM-2475: Loading update to existing package fails if lifecycleStatus or availabilityScope are omitted

service/grails-app/domain/org/olf/erm/Entitlement.groovy, service/src/test/groovy/org/olf/erm/EntitlementSpec.groovy.groovy
fix: Entitlement coverage
Entitlement coverage wasn't working properly with metaClass, have tweaked how they are applied now. Also set up a very basic unit test
ERM-2569
=> ERM-2569: MG/Nolana | Package/Title managed/custom coverage dates from eHoldings not displaying in Agreement Line accordion

service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy
fix: Fixed publicLookup
Fixed an issue where publicLookupwas trying to create an array at the same time as writing to the array and that no longer worked (Seems to have worked at some point in the past, possibly  a change either in compiler or something inside groovy?)
However underlying lookup still isn't behaving as we might expect
ERM-2514
=> ERM-2514: License terms are not displayed in Publication Finder when a journal title is directly linked to an agreement

service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/general/jobs/JobAwareAppender.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
Fixed issue where in certain circumstances MDC `title` field was not being set until AFTER certain log messages were created, causing incorrect additionalInformation fields to show up in log export
ERM-2474
=> fix: MDC title fix

service/grails-app/services/org/olf/PackageIngestService.groovy
fix: MDC ttitle
Remove MDC title before logging certain package-level data
ERM-2474
=> ERM-2474: Local KB admin: Info log export populates title element in additionalInfo with non-relevant data

service/grails-app/views/remoteLicenseLink/_remoteLicenseLink.gson
fix: remoteLicenseLink owner
remoteLicenseLink would not expand owner due to changes made to explicitly render status/amendments in PR 611: https://github.com/folio-org/mod-agreements/pull/611/files#diff-cd4d07b38e259eb6a3c473e46c4597732eadb40f315834625fcd3ad9ac16995e
ERM-2638
=> ERM-2638: No name of linked agreement in license

service/grails-app/views/remoteLicenseLink/_remoteLicenseLink.gson
fix: RemoteLicenseLink note
Fixed issue where RemoteLicenseLink note was not being rendered
ERM-2639
=> ERM-2639: Note not saved with license link

service/build.gradle
* upgrade com.github.jknack:handlebars-helpers to version 4.3.1, refs ERM-2643
=> ERM-2643 handlebars rhino (XML External Entity (XXE) Injection)

service/src/main/groovy/org/olf/dataimport/erm/ErmPackageImplWithContentItems.groovy, service/src/main/groovy/org/olf/dataimport/internal/InternalPackageImplWithPackageContents.groovy
fix: JSON package import fails
Implemented Validatable directly on the extensions of ErmPackageImpl and InternalPackageImpl
ERM-2910
=> ERM-2910: JSON package import fails

service/grails-app/migrations/docs.groovy
fix: Closing }
Fixed migration with missing closing bracket }
ERM-2961
=> ERM-2961: Extend length of document URL to 2048 chars (FIX)

service/grails-app/domain/org/olf/erm/Entitlement.groovy
Added empty array as default for entitlement tags
[ERM-2934](https://issues.folio.org/browse/ERM-2934)
=> ERM-2934 Entitlement tags default

service/grails-app/views/subscriptionAgreement/_subscriptionAgreement.gson
Changed behaviour of expandItems to be set to false by default
[ERM-2992](https://issues.folio.org/browse/ERM-2992)
=> ERM 2992: Default behaviour for Agreements to not expand items

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
chore: accessEnd date guessed for retired title...
Changed log type of "accessEnd date guessed for retired title..." from log.info to log.debug, so these will still appear in module logs, but will no longer appear in job logs. This should dramatically shorten the logs displayed to the user around a specific harvest job.
ERM-3047
=> ERM-3047: Remove "accessEnd date guessed for retired title..." from job logs

service/grails-app/services/org/olf/ErmHousekeepingService.groovy
Updated open access custom property name from Eligible authors to SupportPublishing
[ERM-3044](https://issues.folio.org/browse/ERM-3044)
=> ERM-3044: OpenAccess custom property name

service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
fix: Enrichment fields
Fixed enrichment fields to ensure updates to monograph fields are applied as expected (blank strings bound to null)
Small refactor to reduce repeated code logic
ERM-3018
=> ERM-3018: Implement GOKb Title UUID as primary match ID where available (fix enrichment)

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy
fix: TrustedSourceTI
Changed TrustedSourceTI in fallback to IdFirstTIRS. We don't allow _changes_ to existing TitleInstances that we have matched through the fallback, only changes to title instances we have matched through the Work sourceIdentifier
Added checkForEnrichment in flow once we have a TI in hand and the workSourceIdentifier is null
ERM-3050
=> ERM-3050: Title instance metadata overwritten by non-matching work

service/grails-app/conf/spring/resources.groovy
Set up new environment variables "TIRS" and "INGRESS_TYPE" to allow implementors' dev ops teams to swap at runtime between different methods of ingress and Title resolving
TIRS options as of this PR:
- TitleFirst
- WorkSourceIdentifier
- IdFirst (default)
INGRESS_TYPE options as of this PR:
- PushKB
- Harvest (default)
FOLIO-515
=> feat: Resources use ENV_VARS

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/TitleFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy
chore: TIRS Logging
Added some small logging additions to the TIRSs so we can better tell which TIRS is in use at any given time
This manifests as `log.debug("WorkSourceIdentifierTIRS::resolve(${citation})");` (Or IdFirstTIRS etc) at the top of each citation ingested. Whilst noisy, this is not reflected in the user facing logs, only the module running logs.
ERM-3087
=> ERM-3087: Add debug message to indicate ingest mode

service/grails-app/domain/org/olf/general/StringTemplate.groovy, service/grails-app/migrations/update-mod-agreements-6-0.groovy
Updated column mapping and defaultInternalValue for StringTemplate.Context, written migration for all missing entries, renamed column within string_template table and migrated foreign key constraint
[ERM-3063](https://issues.folio.org/browse/ERM-3063)
=> ERM-3063: StringTemplate.Context refdata should be internal

service/grails-app/conf/logback-development.xml, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy
We now split out the sibling match HQL into two disparate queries, in order to force postgres to perform as two linear queries rather than one nested subquery
=> fix: Split out siblingMatch HQL

service/grails-app/conf/spring/resources.groovy
We change the default TIRS (including on the snapshot/snapshot2 reference envs) to WorkSourceIdentifierTIRS. To get back old behaviour implementors MUST use TIRS='IdFirst' environment variable
=> feat: Change default TIRS

service/grails-app/domain/org/olf/general/jobs/PackageIngestJob.groovy, service/grails-app/domain/org/olf/general/jobs/PersistentJob.groovy, service/grails-app/services/org/olf/KbHarvestService.groovy, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy
Add onInterrupted hook to PersistentJob, which uses the closure mechanism already in place for "work", thereby alllowing JobRunnerService to control the beans the implementing job has access to.
Implement onInterrupted for PackageIngestJob, allowing for the resetting to idle of an external KB when a job has been interrupted
=> ERM-3152: Ensure external data source set to idle after zombie job found

service/src/main/okapi/ModuleDescriptor-template.json
Fixed an incredibly stupid syntax error caused by leaving a comma in the ModuleDescriptor. Not sure how this didn't break something locally but hey ho
=> fix: Stupid syntax error

service/grails-app/migrations/update-mod-agreements-6-1.groovy
feat: URL length
Increase length of URL for PTI to 2083 characters, to bring in line with accepted browser limits. Raised from 255 characters which caused problems in very select circumstances
ERM-3155
=> ERM-3155: URL on PTI is limited to 255 characters which can lead data ingest to fail if an e-resource has a long URL

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy
Previously WorkSourceIdentifierTIRS used check `work.sourceIdentifier = null` in the HQL statement, assuming that the Hibernate query language and GORM would play nicely for null check. This was incorrect however, so it has been swapped for a more direct count, of the number of Works LEFT JOIN the IdentifierOccurrences, where the IdentifierOccurrence is null.
NOTE: This will only work so long as Work only has a single IdentifierOccurrence attached to it in this manner. Reworks will be needed if this changes.
ERM-3177
=> fix: ERM-3177: Check on `noSICount` in WorkSourceIdentifierTIRSImpl is not correct

service/grails-app/services/org/olf/KbHarvestService.groovy
refactor: Additional info.log messages for jobs/processes
Changed log.warn for the interrupted job exception to log.info
ERM-3139
=> ERM-3139: Propose additional info.log messages for jobs/processes

service/build.gradle
build: Dependency upgrades
Updated dependencies as listed in this comment: https://folio-org.atlassian.net/browse/ERM-3174?focusedCommentId=206688
This prevents several security issues
ERM-3174
=> ERM-3174: Review outdated/vulnerable dependencies in mod-agreements

service/src/main/okapi/ModuleDescriptor-template.json
fix: Removed unused codex endpoints
Codex permissions were previously removed but codex endpoints were still included in the module descriptor, these have now been removed
ERM-3157
=> ERM-3157: Missed declaration of backend permissions

service/build.gradle, service/grails-app/services/org/olf/KbHarvestService.groovy
refactor: Remotekb id warning
Expanded upon the runsync warning to include the remotekb id
ERM-3191
=> ERM-3191: Add logging to support issue triage for HibernateOptimisticLockingFailureException

service/build.gradle, service/grails-app/services/org/olf/general/jobs/JobRunnerService.groovy
fix: Changed transaction handling in JobRunnerService
Spring @Transactional annotation does not apply on `protected` or `private` methods. Previously Grails 5 either permitted this or this being ignored did not cause us an issue. However with grails 6 the handling of transactions has changed, and so we need to explicitly wrap the execution of the job in a GormUtils withNewReadOnlyTransaction.
Also increased the heap size in build.gradle for developers running the module using bootRun, to 1.5G
ERM-3190
=> ERM-3190: DB connections are not being released

service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy, service/grails-app/controllers/org/olf/UrlMappings.groovy, service/grails-app/views/ermResource/_ermResource.gson, service/grails-app/views/packageContentItem/_minimalPackageContentItem.gson, service/grails-app/views/pkg/_pkg.gson, service/grails-app/views/subscriptionAgreement/staticCurrentResources.gson, service/grails-app/views/subscriptionAgreement/staticDroppedResources.gson, service/grails-app/views/subscriptionAgreement/staticFutureResources.gson, service/grails-app/views/subscriptionAgreement/staticResources copy.gson
feat: Direct resources on an agreement
Added new "static" endpoints for fetching resources on an agreement directly via HQL, which do not include PTI links
Added new minimalView paramter to endpoints going through ermResource view file, which when the class is a PCI will refer instead to a minimalised PCI view file, cutting time off render.
ERM-3187
=> ERM-3187: Re-write query to show "list of resources in an agreement" for improved performance

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy
BaseTIRS enrich title previously checked whether any changes had occurred before saving a TitleInstance. However it was checking eg "book" against "Book", so would _always_ trigger a save.
=> fix: Enrich Title

service/grails-app/conf/logback-development.xml, service/grails-app/services/org/olf/TitleEnricherService.groovy, service/grails-app/services/org/olf/TitleIngestService.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy, service/src/main/okapi/tenant/sample_data/_data.groovy
Tweaked IDFirstTIRS
- Each sibling creation now does not happen in its own session, allowing any changes to the Work up above to be present for each sibling.
- Fixed issue where attempting to create a TIRS exception would instead throw an exception because String does not have an id... whoops...
- Fixed issue where a certain fallback branch still used TitleInstance instead of String (TitleInstance id)
- Improved logging:
- IdFirstTIRS now explains where each match came from (class one vs sibling vs fuzzy title)
- Turned off log debug in TitleEnricherService, since it _never_ actually does work nowadays
- Turned off GrailsDomainRefdataHelper logging for developers by default, as it clogs up the logs something fierce. Can be turned back by setting back to INFO or above.
=> ERM-3254: With WorkSourceIDTIRS for GOKb we see "Field error in object" errors

service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy
Previously citations caused issues if they were enriching _without_ instancePublicationMedia, which should be a rare occasion. Fixed this
* Also cleared up very old ToDo comment asking for clarification on what instancePublicationMedia enrichming meant for our software -- left new comment clarifying (hopefully)
ERM-3274
=> fix: BaseTIRS NullPointerException

service/build.gradle
build: removed direct commons fileupload dep
Removed dependency that AFAICS we're not using. It will still be pulled in (At a higher version) as part of grails, and we're using our own homebrewed fileUpload service anyway, so this shouldn't impact anything at all
ERM-3225
=> ERM-3225: Upgrade commons-fileupload from 1.4 to 1.5 fixing FileUpload DoS CVE-2023-24998

.github/workflows/int-tests.yml, service/build.gradle
now should download all artifacts in one fell swoop, and should show up number of available processors
=> chore: Small tweaks to github actions

service/src/main/okapi/ModuleDescriptor-template.json
- Remove the erm.files.view subpermission from erm.files.item.download perm in mod-licenses module descriptor
- Update the permissionsRequired for both these endpoint to a new permission erm.agreements.validate which should be defined with no sub permissions
- Add erm.agreements.validate as a sub permission of erm.agreements.edit 
- Update the permissionsRequired for both these endpoint to a new permission erm.kbs.validate which should be defined with no sub permissions
- Add erm.kbs.validate as a sub permission of erm.kbs.edit
=> ERM-3288/3289/3291: Fix validate and download endpoint permissions

service/grails-app/conf/application-dc.yml, service/grails-app/conf/application-rancher-desktop-db.yml, service/grails-app/domain/org/olf/kb/Identifier.groovy, service/grails-app/services/org/olf/IdentifierService.groovy, service/src/integration-test/groovy/org/olf/Agreements/AgreementLifecycleSpec.groovy, service/src/integration-test/groovy/org/olf/BaseSpec.groovy, service/src/integration-test/groovy/org/olf/General/IdentifierServiceSpec.groovy, service/src/integration-test/groovy/org/olf/General/PlatformSpec.groovy, service/src/integration-test/groovy/org/olf/General/TitleServiceSpec.groovy, service/src/integration-test/groovy/org/olf/StringTemplate/StringTemplateBulkSpec.groovy, service/src/integration-test/groovy/org/olf/TIRS/IdFirstTIRS/IdFirstTIRSSpec.groovy, service/src/integration-test/groovy/org/olf/TIRS/TIRSSpec.groovy, service/src/integration-test/groovy/org/olf/TIRS/WorkSourceIdentifierTIRS/WorkSourceIdentifierTIRSSpec.groovy, service/src/integration-test/resources/packages/idFirstTIRS/citations/fix_equivalent_ids.json, service/src/integration-test/resources/packages/idFirstTIRS/citations/fix_equivalent_ids_2.json, service/src/integration-test/resources/packages/idFirstTIRS/citations/fix_equivalent_ids_3.json, service/src/integration-test/resources/packages/idFirstTIRS/ifitirs_pkg.json, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/BaseTIRS.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/TitleFirstTIRSImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/WorkSourceIdentifierTIRSImpl.groovy, service/src/main/groovy/org/olf/kb/IdentifierException.groovy
- Performance tweak to deduplicateList method
- Fix for buildIdentifierHQL in cases where it is called with multiple identifiers (which atm we shouldn't hit anyway, but was logically flawed and could have caused us issues down the road)
- TODO IdentifierService method which can "fix" a multiple identifier exception in the case of issn/eissn/pissn or isbn/eisbn/pisbn
=> ERM-3281: Design and implement process to resolve eissn, pissn, eisbn and pisbn namespaces

service/grails-app/services/org/olf/PackageIngestService.groovy
Tiny tweak to processing message, saving calculation to be done in ms at the end for greater accuracy around per-title averages, allowing for a better picture of performance gains/hits when changes are made
=> chore: Tweaked processing log message

service/grails-app/services/org/olf/PackageIngestService.groovy
In long running transactions by default hibernate objects are left in a cache even after commit. This will cause memory to balloon, especially when ingesting. This patch clears the cache eagerly to maintain memory at lower levels.
=> chore: Clear session after adding titles and packages in order to flush cache

service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
fix: Multiple coverage statements
Ensure we provide _all_ coverage statements passed by GoKB through to the ingest service, instead of smushing them all into one as we erroneously did before
ERM-3284
=> ERM-3284: GOKb ingest process should handle multiple coverage statements on a single TIPP/PCI

service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy
Ensured that calculateCoverage changes get _properly_ propogated through the heirachy. Previously changes would be one transaction behind because the flush hadn't taken hold yet. The reliance on flushes here is not ideal, but at least this works
=> fix: ERM-3308 fix: Coverage not propogated to TIs

service/grails-app/services/org/olf/ErmHousekeepingService.groovy
Removed the authoridentification supplementary property from the mod-agreements ErmHousekeepingService
Removed the AuthIdent reference data category and all related values from the mod-agreements ErmHousekeepingService
Updated the SupportPublishing supplementary property to be primary = false
[ERM-3299](https://folio-org.atlassian.net/browse/ERM-3299)
=> ERM-3299: Minimise supplementary term data populated as reference data

service/grails-app/domain/org/olf/kb/CoverageStatement.groovy, service/grails-app/services/org/olf/CoverageService.groovy, service/grails-app/services/org/olf/UtilityService.groovy, service/src/main/groovy/org/olf/dataimport/erm/CoverageStatement.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy, service/src/main/okapi/tenant/sample_data/_data.groovy
Fixes issue with coverage calculation when resource coverage already exists
Major tweaks to logging... only log coverage issues 1 time, change over to including the failing coverage and the revert set so the users can point to the resource where coverage may not be "up to date" with gokb
refs ERM-3308
=> ERM-3308: Coverage tweaks

service/grails-app/services/org/olf/TitleIngestService.groovy, service/src/main/groovy/org/olf/dataimport/internal/titleInstanceResolvers/IdFirstTIRSImpl.groovy
Turn off two of the loudest logging messages that don't really give us any developer information
=> chore: Turn off two logging messages

service/grails-app/migrations/correct-gin-indices-pre-poppy.groovy, service/grails-app/migrations/correct-gin-indices-pre-quesnalia.groovy, service/grails-app/migrations/module-tenant-changelog.groovy
Inserted migration files prior to `update-mod-agreements-6-0.groovy` and `add-quesnalia-indices-and-fk-constraints.groovy` files. These contain index definitions set up _before_ the non-trigramised (not sure if that's a word) versions in those files. This _should_ allow institutions who have already run these migrations to continue to work with the indices in place (Although we heavily recommend an operational task to bring those in line with the "tip of master" code, while allowing those institutions who are currently prevented from upgrading to do so as normal.
This is a slight misuse of migrations to accommodate this unfortunate gap between institutions who have already upgraded and those who have not.
NOTE: This does _not_ fix the issue where column `sa_name` on …
=> fix: Migrations pre-breaking GIN index insertion

NEWS.md, service/build.gradle, service/gradle.properties, service/src/main/okapi/ModuleDescriptor-template.json
Updated NEWS.md, bumped version -> 7.1.0
ERM-3259
=> Release 7.1.0

service/src/main/okapi/ModuleDescriptor-template.json
build: Add optional okapi dependencies to ModuleDescriptor
ERM-3425
=> ERM-3425: Missing interface dependencies in module descriptor in mod-agreements

service/grails-app/services/org/olf/DependentModuleProxyService.groovy, service/grails-app/services/org/olf/general/pushKB/PushKBService.groovy
Impropve transaction handling in a couple of key areas to facilitate pushPkg functionality -- matches changes made in ingest process and for pushPCI previously
ERM-3455
=> perf: pushPkg endpoint in mod-agreements works unexpectedly slowly

NEWS.md, README.md, service/gradle.properties, service/src/main/groovy/org/olf/export/KBart.groovy
Added NEWS section and bumped version to 7.1.3
ERM-3454
=> Release 7.1.3

service/grails-app/views/usageDataProvider/_usageDataProvider.gson
Originally the erm/entitlements endpoint would return invalid JSON on an agreement with > 2 agreement lines and a usageDataProvider, due to an inherent bug within the grails-views plugin, the usageDataProvider view gson is now more explicitly typed to prevent this
ERM-3464
=> fix: /erm/entitlements API returns invalid JSON data

service/build.gradle
feat: S3 Environment variable
Now available via WTK 10.1.0 -- the ability to set a GLOBAL_S3_SECRET_KEY which acts as a _fallback_ for all tenants if the pre-existing AppSetting is not set.
refs ERM-3470
=> ERM-3470: S3 environment variable settings

service/grails-app/controllers/org/olf/PackageController.groovy, service/grails-app/domain/org/olf/kb/Pkg.groovy, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-agreements-7-2.groovy, service/grails-app/services/org/olf/ImportService.groovy, service/grails-app/services/org/olf/PackageIngestService.groovy, service/src/main/groovy/org/olf/dataimport/erm/ErmPackageImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/HeaderImpl.groovy, service/src/main/groovy/org/olf/dataimport/internal/PackageSchema.groovy, service/src/main/groovy/org/olf/kb/adapters/GOKbOAIAdapter.groovy
**feat: Pkg.syncContentsFromSource**
- Created new boolean property on Pkg domain object: syncContentsFromSource. This defaults to `false` on Pkg creation.
- Also added protection to prevent this field being set via Pkg PUT
**feat: ingest syncContentsFromSource=true**
- Set syncContentsFromSource to true when harvesting via normal methods.
- Add syncContentsFromSource to PackageSchema.HeaderSchema, so it is directly settable via JSON (defaults to false)
- JSON import should default to false, but settable via the header
- KBART imports should default to true
=> ERM-3567: Implement boolean “synchronise” property for packages: mod-agreements

service/build.gradle, service/grails-app/conf/application.yml, service/grails-app/services/org/olf/ErmHousekeepingService.groovy
build: Remove string fallbacks for S3 env variable
S3 environment variable should be `null` when it has not been configured.
refs ERM-3470
=> ERM-3470: fix -- remove S3 environment variable string fallback

service/build.gradle
Upgrade mod-agreements by bumping the undertow dependencies.
mod-agreements 7.2.0 has these productionRuntimeClasspath undertow dependencies:
```
+--- org.springframework.boot:spring-boot-starter-undertow -> 2.7.18
|    +--- io.undertow:undertow-core:2.2.28.Final
|    |    +--- org.jboss.logging:jboss-logging:3.4.1.Final -> 3.4.3.Final
|    |    +--- org.jboss.xnio:xnio-api:3.8.7.Final
|    |    |    +--- org.wildfly.common:wildfly-common:1.5.4.Final
|    |    |    +--- org.wildfly.client:wildfly-client-config:1.0.1.Final
|    |    |    |    \--- org.jboss.logging:jboss-logging:3.3.1.Final -> 3.4.3.Final
|    |    |    \--- org.jboss.threads:jboss-threads:2.3.6.Final -> 3.1.0.Final
|    |    |         +--- org.jboss.logging:jboss-logging:3.4.1.Final -> 3.4.3.Final
|    |    |         \--- …
```
=> ERM-3660: Upgrade undertow 2.2.28.Final -> 2.2.37.Final fixing vulns

service/build.gradle
https://folio-org.atlassian.net/browse/ERM-3659
Upgrade some dependencies of mod-agreements fixing vulnerabilities:
Upgrade io.minio:minio from 8.5.1 to 8.5.17.
Upgrade kafka-clients from 3.7.0 to 3.7.2.
Upgrade jackson from 2.13.5 to 2.18.3.
Note that minio 8.5.17 comes with jackson 2.18: https://github.com/minio/minio-java/blob/8.5.17/build.gradle#L57-L59
The kafka-clients upgrade fixes this vulnerability:
* CVE-2024-56128 SCRAM authentication replay attack https://github.com/advisories/GHSA-p7c9-8xx8-h74f
The jackson upgrade fixes this vulnerability:
* numeric type conversion DoS https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538
The upgrades fix these vulnerabilities in transitive dependencies:
snappy-java from 1.1.8.4 to 1.1.10.5 fixing
* CVE-2023-34453 Integer …
=> ERM-3659: minio 8.5.17, kafka-clients 3.7.2, jackson 2.18.3 fixing vulns

.github/workflows/run-int-tests.yml
For details see
* https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
* https://securitylab.github.com/research/github-actions-untrusted-input/
Found be opengrep: https://github.com/opengrep/opengrep-rules/blob/main/yaml/github-actions/security/github-script-injection.yaml
=> Fix testPath shell injection in run-int-tests.yml

.gitignore, service/grails-app/controllers/org/olf/SubscriptionAgreementController.groovy, service/src/integration-test/groovy/org/olf/Agreements/AgreementPublicLookupSpec.groovy, service/src/integration-test/groovy/org/olf/Agreements/AgreementsBaseSpec.groovy, service/src/integration-test/resources/packages/publicLookup/publicLookupPackage1.json, service/src/integration-test/resources/packages/publicLookup/publicLookupPackage2.json, service/src/integration-test/resources/packages/publicLookup/publicLookupPackage3.json, service/src/integration-test/resources/packages/publicLookup/publicLookupPackage4.json, service/src/integration-test/resources/packages/publicLookup/publicLookupPackage5.json, service/src/integration-test/resources/packages/publicLookup/publicLookupPackage6.json
- Adds integration tests based on scenarios in ticket: https://folio-org.atlassian.net/browse/ERM-3726?atlOrigin=eyJpIjoiMWM4YmY5ZGE2MzBiNDdjMzk1ZWM3YTI1M2VlODZjMGMiLCJwIjoiaiJ9
- Makes a second fix to the publicLookup method (should this be a separate PR/ticket? - the error was found while writing integration tests). The error we noticed was that a PCI which is **directly** added as an entitlement to an agreement should be returned by the publicLookup API even if it lies outside the accessStart and accessEnd dates. It is only when the PCI is returned indirectly by the API because it is part of a package, that the filtering based on accessStart and accessEnd dates should be applied. The fix was to remove the accessStart and accessEnd filters on the **direct** PCI part of the query. Query …
=> ERM-3726: Fix publicLookup API behaviour for access & active from/to dates for PCI based agreement lines

service/grails-app/controllers/org/olf/ResourceController.groovy, service/src/integration-test/groovy/org/olf/DeleteResources/NegativeTestSpec.groovy, service/src/integration-test/groovy/org/olf/DeleteResources/ResourceDeletionSpec.groovy, service/src/main/groovy/org/olf/kb/http/response/PackageMarkForDeleteResponse.groovy
- Introduces a "includeIds" boolean parameter check.
- If includeIds is false, the resourceDeletion controller methods call hideIds() on the response object, which sets the resourceIds property to null on both MarkForDeleteResponse and DeleteResponse objects.
=> ERM-3757: Package Deletion: Add Query Parameter for ids in delete response

service/grails-app/services/org/olf/PackageIngestService.groovy
Comments here: https://folio-org.atlassian.net/browse/ERM-3734?focusedCommentId=269735
Tested that new package update works by changing values in pgAdmin and re-running the package ingest, and by changing values for manual package import.
Identifiers and other list/set fields mentioned in discussion and the ticket seem to have the expected behaviour.
=> ERM-3734: sourceTitleCount in package schema header does not update

service/grails-app/controllers/org/olf/ResourceController.groovy, service/grails-app/services/org/olf/ErmResourceService.groovy
MarkForDelete for the package endpoint now passes in the PCIs from all packages at once, which ensures that the correct numbers are shown. However, this means that we only show the total statistics for all packages being deleted, rather than a breakdown.
This response originally:
```
{
"packages": {
"09f0137f-6e20-4a85-82b4-4450ceab99a7": {
"statistics": {
"ti": 7419,
"pci": 5000,
"work": 4993,
"pti": 5000
}
},
"433c1082-156c-45aa-b804-f47b25334649": {
"statistics": {
"ti": 21371,
"pci": 10827,
"work": 10827,
"pti": 10827
}
},
"b799b4b6-845b-4049-9963-d3d9cc06303a": {
"statistics": {
"ti": 11815,
"pci": 6119,
"work": 6119,
"pti": 6119
}
},
"d9b3617b-4ebe-4d74-8f83-78a2d4d3ea55": {
"statistics": {
"ti": 9360,
"pci": 4680,
"work": 4680,
"pti": 4680
}
}, …
```
=> ERM-3763: Package markForDelete can give incorrect outcome when specifying multiple packages

service/grails-app/controllers/com/k_int/accesscontrol/grails/PolicyEngineController.groovy, service/src/main/java/com/k_int/folio/FolioClient.java, service/src/main/java/com/k_int/folio/FolioClientBodyHandler.java, service/src/main/java/com/k_int/folio/FolioClientExecutor.java
When making calls off to acquisition units we get hit with "stream cancelled" exceptions when the thread pool gets over saturated. This is clearly not great, leading to 500s in the UI where things mostly work in the API layer
To attempt to combat this, ensure the Http version is 1.1 not 2, as the latter seems to cause issues
I had set an explicit thread pool for the FolioClient, but I don't know what I'm doing well enough there, so this is provisionally turned off, awaiting some help and explanations.
=> fix: access control stream cancelled

service/build.gradle
Fix to use ReplaceTokens instead of `expand` for properties, as expand is limited to 64k characters and our descriptor will surpass that
=> build: generateDescriptors is limited to 64K chars
